Fix #659 AxiMemorySim for AXI4 specification
SpinalHDL/SpinalHDL pull request #672
Opened 2022-04-01 08:12 UTC by tanhongze

1. support narrow transfer

2. support burst and write strobes

3. support id replying (arid->rid,awid->bid)

4. support read and write response

5. check burst does not cross 4KB boundary

2022-04-01 16:14 UTC, Readon commented
Good work.
Is there any possibility that using Axi4Agent components to construct the Axi4MemorySim so that the code for spec compatibility can be handled only in one group of classes but reimplement them in several files?

2022-04-02 09:33 UTC, tanhongze commented
> Good work. Is there any possibility that using Axi4Agent components to construct the Axi4MemorySim so that the code for spec compatibility can be handled only in one group of classes but reimplement them in several files?

I don't know. I probably do not have enough time to think how to improve this in a few weeks.

2022-04-04 08:08 UTC, Dolu1990 commented
@c-thaler This update AxiMemorySim, good to merge ?

2022-04-04 08:15 UTC, tanhongze commented
Oh, sorry. I lost my last modification in this PR.

2022-04-04 09:06 UTC, tanhongze commented
It should be OK now. 
Should I provide my tester somewhere?

2022-04-06 13:41 UTC, c-thaler commented
Besides the wrong error message I commented on in the code, I'm fine with it.

2022-04-06 13:43 UTC, c-thaler requested changes

2022-04-06 15:44 UTC, tanhongze commented on lib/src/main/scala/spinal/lib/bus/amba4/axi/sim/AxiMemorySim.scala
> +      message   = s"Write request crossing 4k boundary (addr=${address.toHexString}, len=${burstLength.toLong.toHexString}"
You are right. I will fix it.

2022-04-07 08:13 UTC, Dolu1990 commented
> Should I provide my tester somewhere?

The tester is welcome, as long as it take less than 10 seconds to run ^^

2022-04-13 08:27 UTC, Dolu1990 commented
@tanhongze Do you still have the tests ?

2022-04-13 17:22 UTC, tanhongze commented
> @tanhongze Do you still have the tests ?

My tests are too long to run now. Smarter tests without recompiling are needed, I guess. 
Maybe I will put it in the next PR after I rewrite it someday. Is that OK?

2022-04-15 12:07 UTC, Dolu1990 commented
All good, thanks ^^

2022-04-15 12:07 UTC, merged